MF-435 : Move location selection under user profile
openmrs/openmrs-esm-primary-navigation pull request #52
Opened 2021-02-24 18:01 UTC by donaldkibet

### ticket

[MF-435](https://issues.openmrs.org/browse/MF-435)

### What does this PR do?

1. Move location change to user profile
2. Update user profle header panel to match latest designs

### Screenshoon

![screencast 2021-02-24 20-50-54-min](https://user-images.githubusercontent.com/28008754/109044214-309a3b80-76e3-11eb-93fe-338e5d33f0bf.gif)

2021-02-24 19:03 UTC, FlorianRappl commented on src/components/nav-header-panels/user-menu-panel.component.tsx
> +      <Switcher className={styles.switcher} aria-label="Switcher Container">
This link (`Switcher`) incl. all related logic should be provided in form of an extension component. The extension should come from `esm-login`.

Reason: `esm-login` is currently the host for the location picker. If `esm-login` is gone the location picker is gone. If `esm-login` has the picker on a different address, the current implementation won't work either. Only `esm-login` can be responsible for placing a link to the picker in the user profile.

It's also a good time to introduce the desired flexibility here.

2021-02-24 19:05 UTC, FlorianRappl requested changes
This totally goes in the right direction - and I love the implemented design.

Nevertheless, for the app to scale well we now need to start to embrace the extension slot / extension component concept fully.

2021-03-01 12:25 UTC, FlorianRappl commented on src/root.component.tsx
> +  openmrsFetch
Why these changes? I see new imports, but they are not used.

2021-03-01 12:25 UTC, FlorianRappl commented on src/components/nav-header-panels/user-menu-panel.component.tsx
> +        <ExtensionSlot
Can we think a little bit beyond this one use case?

Today, we add the location picker under user profile. Tomorrow, we add some user information. Then in a week, we'll add some audits for the user or anything else. We should not require additional extension slots. One slot should be sufficient...

Naming the slot "location-changer" does not make much sense. I would rather encourage to use names that describe the location - not what we *now* think will enter at this location.

In this case I would expand the usage (including the `Switcher`) and call it "user-panel" or similar. Generally, the idea is to have this part extensible such that new functionality can be provided by other microfrontends in the future.

2021-03-04 09:47 UTC, donaldkibet commented on src/root.component.tsx
> +  openmrsFetch
removed unused imports

2021-03-04 12:20 UTC, FlorianRappl commented on src/index.ts
> +        id: "user-panel-switcher",
Yeah I'd give it a different ID. Maybe `default-user-panel-switcher` or  `standard-user-panel-switcher`.

I guess what is a good convention is:

- For slot names to describe the location / anticipated content of *where* the slot is
- For components to describe the covered functionality *of* the component itself

2021-03-09 19:08 UTC, FlorianRappl commented on src/components/navbar-header-panels/user-menu-panel.component.tsx
> +        extensionSlotName="user-panel-switcher"
It's good. Just add the `-slot` to follow the new naming convention.

2021-03-10 18:47 UTC, FlorianRappl approved these changes
LGTM - thanks!

2021-03-10 18:47 UTC, merged